services:
  app:
    build: .                 # 동일 폴더의 Dockerfile로 이미지 빌드
    ports:
      - '8081:80'
    env_file:
      - discodeit.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}

      # 여기부터 AWS 설정
      AWS_CREDENTIALS_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      AWS_CREDENTIALS_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_BUCKET_NAME}

    depends_on:
      - db
    volumes:
      - app-storage:/app/.discodeit.storage

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - discodeit.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data      # PostgreSQL 데이터 저장소를 컨테이너 밖에 보존하는 설정
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db-data: {}
  app-storage: {}