#spring:
#  application:
#    name: discodeit
#
#discodeit:
#  repository:
#    type: file   # jcf | file
#    file-directory: .discodeit

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: .discodeit.storage
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucket: ${AWS_BUCKET}
      presigned-url-expiration: ${AWS_PRESIGNED_URL_EXPIRATION:600}
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@gmail.com}
    password: ${ADMIN_PASSWORD:1111}

spring:
  profiles:
    active: dev
  servlet:
    multipart:    # binaryContent 활성화
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
  # 캐시 설정
  cache:
#    type: caffeine
    type: redis
    cache-names:
      - users
      - channels
      - notifications
    caffeine:
      spec: >
        maximumSize=100,
        expireAfterAccess=600s,
        recordStats
    redis:
      enable-statistics: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  # kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: discodeit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

management:
  observations:
    annotations:
      enabled: true