#spring:
#  application:
#    name: discodeit
#
#discodeit:
#  repository:
#    type: file   # jcf | file
#    file-directory: .discodeit

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}
    local:
      root-path: .discodeit.storage
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
      bucket: ${AWS_BUCKET}
      presigned-url-expiration: ${AWS_PRESIGNED_URL_EXPIRATION:600}

spring:
  profiles:
    active: prod
  servlet:
    multipart:    # binaryContent 활성화
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace